services:
  bot:
    container_name: app
    working_dir: /app
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - bot_network
    volumes:
      - .:/app
    command: watchmedo auto-restart --recursive --pattern="*.py" -- python bot.py


  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network

  test_db:
    image: postgres:latest
    container_name: test_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB}
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network

volumes:
  postgres_data:
  test_postgres_data:

networks:
  bot_network:
