"""book qr

Revision ID: 5cf5a4f8f0b2
Revises: 733567ada7c5
Create Date: 2025-04-27 17:42:10.171620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf5a4f8f0b2'
down_revision: Union[str, None] = '733567ada7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('qr_code', sa.LargeBinary(), nullable=True))
    op.add_column('locations', sa.Column('qr_code', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'qr_code')
    op.drop_column('locations', 'qr_code')
    # ### end Alembic commands ###
