"""Location columns changed to city(enum), room

Revision ID: 733567ada7c5
Revises: ab369facdc5e
Create Date: 2025-04-07 12:35:11.174532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733567ada7c5'
down_revision: Union[str, None] = 'ab369facdc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('city', sa.Enum('Almaty', 'Berlin', 'Bishkek', 'Bratislava', 'Gdansk', 'Krakow', 'Lodz', 'London', 'Mexico_city', 'New_York', 'San_Francisco', 'Sofia', 'Tashkent', 'Tbilisi', 'Vienna', 'Vilnius', 'Warsaw', 'Wroclaw', name='city', native_enum=False), nullable=False))
    op.add_column('locations', sa.Column('room', sa.String(), nullable=False))
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('locations', 'room')
    op.drop_column('locations', 'city')
    # ### end Alembic commands ###
