"""update categories to enum

Revision ID: ab369facdc5e
Revises: fac7eb737fb2
Create Date: 2025-03-27 01:55:02.089257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab369facdc5e'
down_revision: Union[str, None] = 'fac7eb737fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_categories_category_id_fkey', 'books_categories', type_='foreignkey')
    op.drop_column('books_categories', 'category_id')
    op.drop_table('categories')
    op.add_column('books_categories', sa.Column('category', sa.Enum('PROGRAMMING', 'DATA_SCIENCE', 'MACHINE_LEARNING', 'ARTIFICIAL_INTELLIGENCE', 'CYBERSECURITY', 'SOFTWARE_ENGINEERING', 'DATABASES', 'WEB_DEVELOPMENT', 'DEVOPS', 'ALGORITHMS', name='category', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.add_column('books_categories', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_categories_category_id_fkey', 'books_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('books_categories', 'category')
    # ### end Alembic commands ###
